[variables]
ELECTRON_SKIP_BINARY_DOWNLOAD = "1"
NIXPACKS_NODE_VERSION = "20"

[phases.install]
cmds = ["npm ci --ignore-scripts"]

[phases.build]
cmds = ["npx vite build"]

[start]
cmd = "npx serve dist -s -l 3000"
